### PR TITLE
[OpenCV] Allow version to be overridden

### PR DESCRIPTION
**Pull request by fahhem**

### CODE REVIEW

**Comment by jpieper** [comment]
Do any other versions actually work with the code in the repository?

**Comment by fahhem** [comment]
Yes, we're using 3.4.13. Though, admittedly, we're only using `:core`, `:imgcodecs`, and `:imgproc`, so I can't speak to the other modules working

**Comment by jpieper** [comment]
Sounds good, thanks!

**Comment by fahhem** [comment]
I spoke too soon! It turns out bazel let me build locally, but our CI caught that other targets weren't working with 3.4.13. It needs a lot more dispatched_files, what would you say to upgrading 3.4.2 to 3.4.13 in the repo? Alternatively, I have a little time I can spend on making the dispatched files be auto-detected (by generating the package.BUILD by parsing the CMakeLists file in the repository.bzl)

**Comment by jpieper** [comment]
Either approach is fine by me!

**Pull request merged**
